# Generated by Django 4.0.2 on 2022-02-09 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('farm', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('fermentation', models.TextField()),
                ('coffee_id', models.IntegerField()),
            ],
        ),
    ]
