# Generated by Django 4.0.2 on 2022-02-09 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeApi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffee',
            name='coffee_id',
        ),
    ]
