# Generated by Django 4.0.2 on 2022-02-12 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeApi', '0002_remove_coffee_coffee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='farm',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='region',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
